data_mongo:
    image: busybox
    volumes:
        - /data/db
    command: /bin/true

data_redis:
    image: busybox
    volumes:
        - /data
    command: /bin/true

mongo:
    image: mongo:latest
    volumes_from:
        - data_mongo
    restart: always

redis:
    image: redis:latest
    volumes_from:
        - data_redis
    command: redis-server --appendonly yes
    restart: always

www:
    build: .
    ports:
        - 8080
    links:
        - mongo
        - redis
    env_file: .env.prod
    environment:
        - NODE_ENV=production
        - VIRTUAL_HOST=git-commit.app.docken.xyz
        - VIRTUAL_PORT=8080
        - MONGO_DB=db
    command: npm start
    restart: always
